use_frameworks!

platform :ios, '8.0'

target 'MCSettingsCell_Example' do
  pod 'MCSettingsCell', :path => '../'

  target 'MCSettingsCell_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
