# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: objective-c

notifications:
  email: false


cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:

- set -o pipefail

- echo Check if the library described by the podspec can be built
- pod lib lint --allow-warnings

- echo Build as dynamic frameworks
- xcodebuild build -workspace Example/MCSettingsCell.xcworkspace -scheme 'MCSettingsCell' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty -c

- echo Clean DerivedData
- rm -rf ~/Library/Developer/Xcode/DerivedData/

- echo Build the Demo apps
- xcodebuild build -workspace Example/MCSettingsCell.xcworkspace -scheme 'MCSettingsCell-Example' -destination 'platform=iOS Simulator,name=iPhone 11 Pro' -configuration Debug CODE_SIGNING_ALLOWED=NO | xcpretty -c

- echo Clean DerivedData
- rm -rf ~/Library/Developer/Xcode/DerivedData/
- mkdir DerivedData

